CONFIG_LOG=y

# Subsistemas
CONFIG_INPUT=y
CONFIG_LED=y
CONFIG_LED_STRIP=y
CONFIG_DISPLAY=y
CONFIG_CHARACTER_FRAMEBUFFER=y
CONFIG_SENSOR=y

CONFIG_ZBUS=y
CONFIG_SMF=y
CONFIG_SMF_ANCESTOR_SUPPORT=y
CONFIG_SMF_INITIAL_TRANSITION=y

CONFIG_CONSOLE=y