CONFIG_LOG=y

# Subsistemas
CONFIG_INPUT=y
CONFIG_LED=y
CONFIG_LED_STRIP=y
CONFIG_DISPLAY=y
CONFIG_CHARACTER_FRAMEBUFFER=y
CONFIG_SENSOR=y

# Escolha da imagem para compilar.
CONFIG_APP_FIRMWARE_BRINGUP=y
